### ISSUE TITLE
Closes around 5 seconds after building

### ISSUE THREAD

**Issue by TheSummxr** [hinnie123/splitgate-load-library-injector#1]
Had no issues building and everything seemed fine, but once I try to open the injector it closes after about 5 seconds and doesn't do anything.

**Comment by fir3z** [comment]
https://github.com/hinnie123/splitgate-load-library-injector/blob/main/splitgate-load-library-injector/splitgate-load-library-injector.cpp#L170

**Comment by TheSummxr** [comment]
> https://github.com/hinnie123/splitgate-load-library-injector/blob/main/splitgate-load-library-injector/splitgate-load-library-injector.cpp#L170

ya i tried looking at that but uhhhhh idk anything about coding or c++ specifically, but i made sure just like it says to not have splitgate open or anything like that

**Comment by fir3z** [comment]
have you dragged the dll onto the injector?

**Comment by TheSummxr** [comment]
ive tried to, but the program closes with 3 secs and the one time i got the dll dragged on fast enough it didnt inject and nothing happened

**Comment by TheSummxr** [comment]
should i just change Sleep(3000); to like Sleep(8000); and try again or...

**Comment by TheSummxr** [comment]
> have you dragged the dll onto the injector?
