### ISSUE TITLE
Error MSB88020

### ISSUE THREAD

**Issue by Desparration** [hinnie123/splitgate-load-library-injector#2]
The platform toolset = v143 cannot be found.

**Comment by shadower011** [comment]
change it to v142
![image](https://user-images.githubusercontent.com/67420608/128152062-5d747baf-5f46-474f-b368-57f5d240e5e4.png)

![image](https://user-images.githubusercontent.com/67420608/128151931-06e701a0-2922-4238-93d0-8a024659d22a.png)

**Comment by Desparration** [comment]
Thanks. It worked. :)
